{"title": "FabActUtil.exe exits with code -1", "tags": ["azure-service-fabric"], "creation_date": 1476924173, "score": 1, "body": "<p>Running the command from the error message outside of Visual Studio gave the following message with a stack trace: </p>\n\n<pre><code>System.ArgumentException: An item with the same key has already been     \nadded. \n  at System.ThrowHelper.ThrowArgumentException(ExceptionResource \nresource) \n  at System.Collections.Generic.Dictionary`2.Insert(TKey key, \nTValue value, Boolean add) \n  at Microsoft.ServiceFabric.Actors.Generator.ManifestGenerator.Context.LoadExistingContents() \n  at Microsoft.ServiceFabric.Actors.Generator.ManifestGenerator.Generate(Arguments arguments) \n  at FabActUtil.Tool.GenerateOutput(ToolContext context) \n  at FabActUtil.Program.Main(String[] args)\n</code></pre>\n\n<p>This was due to the <code>ApplicationManifest.xml</code> having a repeated definition for one of the default services.</p>\n\n<p>Thanks to amanbha: <a href=\"https://github.com/amanbha\" rel=\"nofollow\">https://github.com/amanbha</a></p>\n", "last_activity_date": 1476978321, "answer_id": 40143717, "is_accepted": true, "owner": {"user_id": 3524426, "reputation": 418, "user_type": "registered", "accept_rate": 79, "display_name": "Dagrooms", "link": "http://stackoverflow.com/users/3524426/dagrooms", "profile_image": "https://i.stack.imgur.com/kvcU7.jpg?s=128&g=1"}, "last_edit_date": 1476978321, "question_id": 40135077}