{"body": "<p>I <em>cleared</em> my <em>cache</em> in <code>setUp()</code>:</p>\n\n<pre><code>def setUp(self):\n    # cleared cache\n    # in my case: self.redis_conn.flushdb()\n</code></pre>\n\n<p>This solved the problem. You can find a helpful discussion about such a problem associated with <code>assertNumQueries</code> <a href=\"https://code.djangoproject.com/ticket/23746\" rel=\"nofollow\">here</a></p>\n\n<p>Many thanks to @Daniel Hepper for helping me out!!!</p>\n", "tags": ["python", "django", "unit-testing", "assert", "django-tests"], "creation_date": 1476959806, "score": 1, "last_activity_date": 1476959806, "answer_id": 40152014, "is_accepted": false, "owner": {"user_id": 6354622, "reputation": 1183, "user_type": "registered", "accept_rate": 76, "display_name": "User_Targaryen", "link": "http://stackoverflow.com/users/6354622/user-targaryen", "profile_image": "https://i.stack.imgur.com/rNoam.jpg?s=128&g=1"}, "title": "Issue with assertNumQueries", "question_id": 40147274}