{"body": "<ol>\n<li>You cannot get details more than found in this exception</li>\n</ol>\n\n<p>To show real exception loop over innerexceptions until it is null. Then you reached the first one</p>\n\n<ol start=\"2\">\n<li>The exception was thrown from a source class or function then readed by upper level class that throw it with more global details because there is no error handling on the source</li>\n</ol>\n", "tags": ["c#", "exception"], "creation_date": 1477428494, "score": 0, "last_activity_date": 1477428494, "answer_id": 40249421, "is_accepted": false, "owner": {"user_id": 7031230, "reputation": 571, "user_type": "registered", "display_name": "H.Fadlallah", "link": "http://stackoverflow.com/users/7031230/h-fadlallah", "profile_image": "https://www.gravatar.com/avatar/a4dc60c72f95a8ea1106cdd4440234e9?s=128&d=identicon&r=PG&f=1"}, "title": "How get Detail of InnerException", "question_id": 40249344}